### ISSUE TITLE
DSFColorPickerPopover

### ISSUE THREAD

**Issue by Skovie** [dagronf/DSFColorPicker#1]
after upgrading to SPM  I get this when trying to archive my project ...

'guard' body must not fall through, consider using a 'return' or 'throw' to exit the scope
 at line 72  this code bit: 

		let viewController = DSFColorPickerPopoverViewController()
		viewController.configure(name: name)
		guard let vc = viewController.colorView else {
			assert(false)
		}

**Comment by dagronf** [comment]
Hey @Skovie -- thanks for the report!

I believe I've fixed the issue in version 1.2.0 (I just pushed it up a moment ago) - can you update your SPM package to version 1.2.0 and verify?

**Comment by Skovie** [comment]
I’ll do that tomorrow morning it’s 1:30 am and just turned in 😆

**Comment by dagronf** [comment]
No rush mate - all in good time!

**Comment by Skovie** [comment]
it works prefect now :-). thanks, you are already credited in my app ProjectTimeKeeper's  acknowledgments

**Comment by dagronf** [comment]
Brilliant mate. Thanks for the heads up!
